version: '3'
services:
    product-app:
        container_name: product-app
        image: samuelbismuth101/productservice
        restart: on-failure
        ports: 
            - 10666:9090
        environment: 
            WAIT_HOSTS: mysql:3306
        depends_on: 
            - docker-mysql 
            - coupon-app
    coupon-app:
        container_name: coupon-app
        image: samuelbismuth101/couponservice
        restart: on-failure
        ports: 
            - 10555:9091
        environment: 
            WAIT_HOSTS: mysql:3306
        depends_on: 
            - docker-mysql
    docker-mysql:
        container_name: docker-mysql
        image: mysql
        restart: always
        environment: 
            MYSQL_DATABASE: mydb
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ROOT_HOST: '%'
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - 6666:3306
        healthcheck: # Optional element
            test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES \""
            interval: 4s
            timeout: 20s
            retries: 5
        
